### PR TITLE
chore: update docusaurus to beta18

### PR DESCRIPTION
**Pull request by aron**
This fixes the bulk of existing vulnerabilities detected by Snyk (none of these were reachable due to the docs being a static site) but keeps our toolchain up-to-date. I've added entries to the .snyk file for the remaining few to be reviewed in three months time.

I've used the `npm run build` and `npm start` commands to verify the docs work as before with the new version. 

<table><td>
⚠️ Note: It does look like the `docusaurus` command can no longer be run without a second command, I can't see what this used to do nor where it is used so I've removed it from the package.json scripts section.
</td></table>

### CODE REVIEW

**Comment by eliecharra** [comment]
> Note: It does look like the `docusaurus` command can no longer be run without a second command, I can't see what this used to do nor where it is used so I've removed it from the package.json scripts section.

Any idea @wbeuil ?

**Comment by wbeuil** [comment]
@aron all the `docusaurus` scripts are available from their template, we could totally remove some of them if we want.

This is the package.json of the classic template of their newest version https://github.com/facebook/docusaurus/blob/main/packages/create-docusaurus/templates/classic/package.json

They also bump `react` to v17 and added the `prism-react-renderer` package for highlighting codes.

**Comment by aron** [comment]
@wbeuil oh that's super useful to know, thank you! I'll take a look at this

**Review by wbeuil — APPROVED** [review]
LGTM, can't figure out why the check failed at install packages ..

**Comment by wbeuil** [comment]
For those wondering why it fails on [this check](https://github.com/snyk/driftctl-docs/actions/runs/2110234498) it's because the command `npm ci`, which is a good practice to install node dependencies in a ci environment, highlights a bug where the project needs to have a `name` in its `package.json` file ... still a bug in 2022

Ping @aron since you wanted to remove the `name` attribute in the first place :)

https://stackoverflow.com/a/60112825

**Pull request merged**
